import { z } from "zod";

export const settingsSchema = z.object({
  initialBalance: z.coerce.number().min(0),
  currency: z.string().trim().min(1).max(8).transform((value) => value.toUpperCase()),
  timezoneOffset: z.string().trim().min(3).max(16),
  dateFormat: z.enum(["DD/MM/YYYY", "MM/DD/YYYY", "YYYY-MM-DD"]),
  timeFormat: z.enum(["12-hour", "24-hour"]),
  autoTradeNumber: z.boolean(),
  defaultTimeframe: z.string().trim().min(1).max(12),
  defaultSymbol: z.string().trim().max(24).transform((value) => value.toUpperCase()),
  defaultCommission: z.coerce.number(),
  defaultSwap: z.coerce.number(),
  themeMode: z.enum(["light", "dark", "system"]),
  accentColor: z.string().trim().min(1).max(32),
  aiProvider: z.enum(["openai", "gemini"]),
  aiModel: z.string().trim().max(100),
  enableScreenshotAnalysis: z.boolean(),
  saveAiAnalysisHistory: z.boolean(),
  maxRiskPerTradePercent: z.coerce.number().min(0),
  maxDailyLossPercent: z.coerce.number().min(0),
  maxWeeklyLossPercent: z.coerce.number().min(0),
  maxTradesPerDay: z.coerce.number().int().min(0),
  maxLosingStreakWarning: z.coerce.number().int().min(0),
  minimumRiskRewardRatio: z.coerce.number().min(0),
  enableRiskWarning: z.boolean(),
});
