import { z } from "zod";

export const tradeSchema = z.object({
  id: z.string().min(1),
  tradeNumber: z.coerce.number().int().nonnegative(),
  date: z.string().min(1),
  time: z.string().min(1),
  timestamp: z.coerce.number().nonnegative(),
  symbol: z.string().trim().min(1).max(24).transform((value) => value.toUpperCase()),
  direction: z.enum(["Buy", "Sell"]),
  timeframe: z.enum(["M1", "M5", "M15", "M30", "H1", "H4", "D1", "W1", "MN1"]),
  entryPrice: z.coerce.number().positive(),
  stopLoss: z.coerce.number().nonnegative(),
  takeProfit: z.coerce.number().nonnegative(),
  lotSize: z.coerce.number().positive(),
  riskAmount: z.coerce.number().nonnegative(),
  rewardAmount: z.coerce.number().nonnegative(),
  grossProfitLoss: z.coerce.number(),
  commission: z.coerce.number(),
  swap: z.coerce.number(),
  netProfitLoss: z.coerce.number(),
  withdrawalAmount: z.coerce.number().nonnegative(),
  startingBalance: z.coerce.number().nonnegative(),
  endingBalance: z.coerce.number(),
  growthPercent: z.coerce.number(),
  riskRewardRatio: z.coerce.number(),
  rMultiple: z.coerce.number(),
  status: z.enum(["Win", "Loss", "Breakeven", "Running", "Cancelled"]),
  strategyName: z.string().max(200),
  strategyId: z.string().optional(),
  setupType: z.string().max(200),
  emotionBefore: z.string().max(500),
  emotionAfter: z.string().max(500),
  mistakeMade: z.string().max(1000),
  lessonLearned: z.string().max(1000),
  notes: z.string().max(5000),
  beforeScreenshotUrl: z.string().url().optional(),
  afterScreenshotUrl: z.string().url().optional(),
  checklistTrendConfirmed: z.boolean(),
  checklistKeyLevelConfirmed: z.boolean(),
  checklistEntryReasonConfirmed: z.boolean(),
  checklistStopLossPlanned: z.boolean(),
  checklistTakeProfitPlanned: z.boolean(),
  checklistRiskAccepted: z.boolean(),
  checklistNoRevengeTrade: z.boolean(),
  checklistNoOverlot: z.boolean(),
  checklistNewsChecked: z.boolean(),
  checklistEmotionStable: z.boolean(),
  checklistScore: z.coerce.number().min(0).max(10),
  checklistStatus: z.enum(["Plan Passed", "Plan Warning"]),
  mistakeTags: z.array(z.string()).default([]),
  ruleFollowed: z.enum(["Yes", "No", "Partially"]),
  ruleBrokenNotes: z.string().max(1000),
  tradeQualityScore: z.coerce.number().min(0).max(100),
  tradeQualityGrade: z.enum(["A+", "A", "B", "C", "D"]),
  reviewCompleted: z.boolean(),
  reviewDate: z.string(),
  reviewNotes: z.string().max(5000),
  createdAt: z.coerce.number().nonnegative(),
  updatedAt: z.coerce.number().nonnegative(),
});

export const withdrawalSchema = z.object({
  amount: z.coerce.number().positive(),
  withdrawnAtLocal: z.string().min(1),
  timezoneOffsetMinutes: z.coerce.number().int().min(-840).max(840),
  note: z.string().max(1000).optional(),
});

export const strategySchema = z.object({
  name: z.string().trim().min(1).max(120),
  description: z.string().max(3000).default(""),
  marketConditions: z.string().max(2000).default(""),
  entryRules: z.array(z.string()).default([]),
  exitRules: z.array(z.string()).default([]),
  riskRules: z.array(z.string()).default([]),
  tags: z.array(z.string()).default([]),
  isActive: z.boolean().default(true),
});
