export const tradeDirections = ["Buy", "Sell"] as const;
export const tradeTimeframes = ["M1", "M5", "M15", "M30", "H1", "H4", "D1", "W1", "MN1"] as const;
export const tradeStatuses = ["Win", "Loss", "Breakeven", "Running", "Cancelled"] as const;
export const checklistStatuses = ["Plan Passed", "Plan Warning"] as const;
export const ruleFollowedStatuses = ["Yes", "No", "Partially"] as const;
export const tradeQualityGrades = ["A+", "A", "B", "C", "D"] as const;
export const screenshotSlots = ["beforeEntry", "afterEntry"] as const;

export type TradeDirection = (typeof tradeDirections)[number];
export type TradeTimeframe = (typeof tradeTimeframes)[number];
export type TradeStatus = (typeof tradeStatuses)[number];
export type ChecklistStatus = (typeof checklistStatuses)[number];
export type RuleFollowed = (typeof ruleFollowedStatuses)[number];
export type TradeQualityGrade = (typeof tradeQualityGrades)[number];
export type ScreenshotSlot = (typeof screenshotSlots)[number];

export type TradeScreenshot = {
  id: string;
  slot: ScreenshotSlot;
  name: string;
  dataUrl: string;
  createdAtLocal: string;
};

export type Trade = {
  id: string;
  tradeNumber: number;
  date: string;
  time: string;
  timestamp: number;
  symbol: string;
  direction: TradeDirection;
  timeframe: TradeTimeframe;
  entryPrice: number;
  stopLoss: number;
  takeProfit: number;
  lotSize: number;
  riskAmount: number;
  rewardAmount: number;
  grossProfitLoss: number;
  commission: number;
  swap: number;
  netProfitLoss: number;
  withdrawalAmount: number;
  startingBalance: number;
  endingBalance: number;
  growthPercent: number;
  riskRewardRatio: number;
  rMultiple: number;
  status: TradeStatus;
  strategyName: string;
  strategyId?: string;
  setupType: string;
  emotionBefore: string;
  emotionAfter: string;
  mistakeMade: string;
  lessonLearned: string;
  notes: string;
  beforeScreenshotUrl?: string;
  afterScreenshotUrl?: string;
  checklistTrendConfirmed: boolean;
  checklistKeyLevelConfirmed: boolean;
  checklistEntryReasonConfirmed: boolean;
  checklistStopLossPlanned: boolean;
  checklistTakeProfitPlanned: boolean;
  checklistRiskAccepted: boolean;
  checklistNoRevengeTrade: boolean;
  checklistNoOverlot: boolean;
  checklistNewsChecked: boolean;
  checklistEmotionStable: boolean;
  checklistScore: number;
  checklistStatus: ChecklistStatus;
  mistakeTags: string[];
  ruleFollowed: RuleFollowed;
  ruleBrokenNotes: string;
  tradeQualityScore: number;
  tradeQualityGrade: TradeQualityGrade;
  reviewCompleted: boolean;
  reviewDate: string;
  reviewNotes: string;
  createdAt: number;
  updatedAt: number;
};

export type Withdrawal = {
  id: string;
  amount: number;
  withdrawnAtLocal: string;
  timezoneOffsetMinutes: number;
  note?: string;
  createdAtLocal: string;
};
